# Generated by Django 2.0.7 on 2018-07-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackprofile',
            name='last_login_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
