# Generated by Django 2.0.7 on 2018-07-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0002_slackprofile_last_login_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('time_decription', models.CharField(max_length=255, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_signin.SlackProfile')),
            ],
        ),
    ]
