# Generated by Django 2.0.7 on 2018-07-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0003_signinrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signinrecords',
            old_name='time',
            new_name='in_time',
        ),
    ]
