# Generated by Django 2.0.7 on 2018-07-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0004_auto_20180704_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinrecords',
            name='date_in',
            field=models.DateField(null=True),
        ),
    ]
