# Generated by Django 2.0.7 on 2018-07-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0005_signinrecords_date_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signinrecords',
            old_name='time_decription',
            new_name='time_description',
        ),
    ]
