# Generated by Django 2.0.7 on 2018-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0006_auto_20180704_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventmesssage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_msg_id', models.CharField(max_length=255, null=True, unique=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('channel', models.CharField(max_length=255, null=True)),
                ('event_ts', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
