# Generated by Django 2.0.7 on 2018-07-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0007_eventmesssage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedHostsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addrr', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
