# Generated by Django 2.0.7 on 2018-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_signin', '0008_allowedhostsaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinrecords',
            name='date_str',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
